version: "3"
services:

  mongodb:
    hostname: easytravel-mongodb
    container_name: mongodb
    image: dynatrace/easytravel-mongodb
    ports:
      - "27017"
      - "28017"

  backend:
    hostname: easytravel-backend
    container_name: backend
    image: "dynatrace/easytravel-backend"
    ports:
      - "8080"
    networks:
      - mongodb
    environment:
      ET_DATABASE_LOCATION: "easytravel-mongodb:27017"

  frontend:
    hostname: easytravel-frontend
    container_name: frontend
    image: dynatrace/easytravel-frontend
    ports:
      - "8080"
    networks:
      - backend
      - mongodb
    environment:
      ET_BACKEND_URL: "http://easytravel-backend:8080"

  www:
    hostname: easytravel-www
    container_name: www
    image: dynatrace/easytravel-nginx
    ports:
      - "80"
    networks:
      - frontend
      - backend
    environment:
      ET_FRONTEND_LOCATION: "easytravel-frontend:8080"
      ET_BACKEND_LOCATION: "easytravel-backend:8080"

  loadgen:
    container_name: loadgen-dt
    image: emperorwilson/easytravel-loadgen-dt
    networks:
      - backend
      - frontend
      - www
    environment:
      ET_FRONTEND_URL: "http://easytravel-www:80"
      ET_BACKEND_URL: "http://easytravel-www:8080"
      ET_PROBLEMS: "BadCacheSynchronization,CPULoad,DatabaseCleanup,DatabaseSlowdown,ExceptionSpamming,FetchSizeTooSmall,JourneySearchError404,JourneySearchError500,LoginProblems,MediumMemoryLeak,MobileErrors,TravellersOptionBox"
